services:
  node:
    container_name: node
    build: .
    image: fullstack/backend
    networks:
      - fullstack-network
    ports:
      - 5000:5000
    env_file:
      - .env

networks:
  fullstack-network:
    name: fullstack-network
    driver: bridge