on:
  push:
    branches:
      - main
name: Build and Deploy Back-end on AWS
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create back-end env file
        uses: SpicyPizza/create-envfile@v1.3.1
        with:
          envkey_PORT: ${{secrets.PORT}}
          envkey_MONGO_URI: ${{secrets.MONGO_URI}}
          envkey_MONGO_URI_PRISMA: ${{secrets.MONGO_URI_PRISMA}}
          envkey_JWT_SECRET: ${{secrets.JWT_SECRET}}
          file_name: .env
          fail_on_empty: true
      - name: Build
        run: docker compose build
      - name: Run
        run: docker compose down && docker compose up -d
    
