name: PR
on: [pull_request]
jobs:
  runs-on: ubuntu-latest
  steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Make a new envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_PORT: 5000
        envkey_MONGO_URI: "mongodb+srv://lacopaback:lucaselucas@lacopa.7ubzeeh.mongodb.net/"
        envkey_MONGO_URI_PRISMA: "mongodb+srv://lacopaback:lucaselucas@lacopa.7ubzeeh.mongodb.net/musichems"
        envkey_JWT_SECRET: "top_secret"
        file_name: .env.test
    - name: Run tests
      run: docker-compose -f docker-compose-test.yml run node npm run test